train:
  epochs: 75
  batch_size: 4
  mode: as # ef|ssl|as
  seed: 0
  visualize: False

  wandb_run_name: as_sweep
  wandb_mode: online
  wandb_log_steps: 500
  wandb_group_name: experiment_as_sweeps
  wandb_entity: madmas
  use_wandb: True

  optimizer:
    lr: 0.00001
    weight_decay: 0.000001

  scheduler:
    patience: 10
    threshold: 0.01
    min_lr: 0.000001

  criterion:
    attn_lambda: 0.0
    frame_lambda: 0.0
    classification_lambda: 0.0

  evaluator:
    standards: ["acc"] # Can include mae, r2, f1, acc
    eval_metric: acc # Must be one of values specified in standards
    maximize: True

model:
  checkpoint_path:

  # STE Config
  patches: [16, 16] # Size of each patch in the image
  spatial_num_layers: 12
  spatial_mlp_dim: 3072
  spatial_num_heads: 12
  spatial_aggr_method: cls
  spatial_hidden_size: 768
  spatial_dropout_rate: 0.2
  pretrained_patch_encoder_path: /scratch/st-puranga-1/users/masoud19/workspace/heart-transformer/pretrained_models/B_16.pth # Will use pretrained transformer if specified

  # TTE Config
  temporal_num_layers: 2
  temporal_mlp_dim: 128
  temporal_num_heads: 4
  temporal_aggr_method: cls
  temporal_dropout_rate: 0.2
  temporal_hidden_size: 768

  # VTE Config
  vid_num_layers: 2
  vid_mlp_dim: 256
  vid_num_heads: 4
  vid_aggr_method: cls
  vid_dropout_rate: 0.2
  vid_hidden_size: 768

  output_dropout_rate: 0.2

data:
  name: as
  dataset_path: /arc/project/st-puranga-1/datasets/aortic-stenonsis/round2
  frame_size: 224
  max_frames: 144 # Number of samples prior to subsampling
  n_sampled_frames: 32 # Number of frame to subsample
  max_clips: 4 # Number of back to back clips to extract per video
  mean: 0.0857377 # for echonet: 0.1292275 | for AS: 0.0857377
  std: 0.1708384 # for echonet: 0.1902375 | for AS: 0.1708384
