train:
  epochs: 1000
  batch_size: 10
  mode: as
  seed: 0

  wandb_project_name: MetaformerGNN
  wandb_run_name: purang_32_large_model
  wandb_mode: online
  wandb_log_steps: 1 # Log every n steps
  wandb_group_name: experiment # bunch multiple runs into a group
  wandb_entity: nimako 
  use_wandb: False

  optimizer:
    lr: 0.001
    weight_decay: 0.0001

  scheduler:
    patience: 10
    threshold: 0.01
    min_lr: 0.0000001

  criterion:
    classification_lambda: 1

  evaluator:
    standards: ["acc", "mae", "bacc"] # Can include mae, r2, f1, acc
    eval_metric: acc # Must be one of values specified in standards
    maximize: True

model:
  checkpoint_path: # Must be specified for testing. Optional for training.
  num_classes: 4
  sub_models:
    - backbone  
    - gnn
    # - pc
  backbone:
    pretrained: True
    embedding_size: 128

  gnn:
    channel_list: [256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256]
    num_classes: 4
    # the length of heads must be one item smaller than the channels list
    heads: [12, 12, 12, 12, 12, 12, 12, 12, 12, 12]
    do_prob: 0.3

  pc:
    in_channels: 6
    out_channels: 128
    num_layers: 12
    hidden_dim: 256
    num_heads: 12
    dropout: 0.3

data:
  name: as # as|echonet|biplane
  dataset_path: /mnt/data/
  # dataset_filename: annotations-all.csv
  # dataset_path: /arc/project/st-puranga-1/datasets/aortic-stenonsis/round2
  frame_size: 224
  max_frames: 32 # Number of samples prior to subsampling
  n_sampled_frames: 32 # Number of frame to subsample
  max_clips: 2 # Number of back to back clips to extract per video
  mean: 0.0857377 # for echonet: 0.1292275 | for AS: 0.0857377
  std: 0.1708384 # for echonet: 0.1902375 | for AS: 0.1708384
  use_metadata: True
